### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by zudov** [philopon/barrier#1]
Hi. Thanks for that package, works exactly as needed so far.

We are going to use it in https://github.com/fpco/stackage-server/pull/132. And it would be much nicer if `barrier` itself was present on stackage.

It would be really great if you could add `barrier` to stackage with yourself as a maintainer. If not, I'd be glad to do it myself.

Please tell what you think.

**Comment by zudov** [comment]
https://github.com/fpco/stackage/pull/914

**Comment by philopon** [comment]
Sorry for the delay in answering...
I'm going to be maintainer of `barrier` on stackage:smile:
Could you close your PR on stackage?

**Comment by zudov** [comment]
That's great. Thanks.
